### ISSUE TITLE
should not use Moops?

### ISSUE THREAD

**Issue by karupanerura** [rustyconover/amazon-ses#1]
https://metacpan.org/pod/Moops is unstable:

```
STATUS

Unstable.
Will probably never be stable.
```

**Comment by rustyconover** [comment]
In retrospect I agree, but this module hasn't been updated in so long.  Personally, I've mostly moved to using node.js which has a AWS SDK that is more fully featured.  Sorry I'm not more helpful.

**Comment by karupanerura** [comment]
It's bad news for us... ok. thank you.
